baseURL: "https://blog.vitaliitylyk.com/"
title: Vitalii Tylyk
paginate: 5
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: GTM-W3HBZZ

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: Vitalii Tylyk | .NET / Sitecore / Architecture / DevOps
  description: ".NET / Sitecore / Architecture / DevOps on Vitalii Tylyk&#8230;"
  keywords: [Blog, Portfolio, PaperMod]
  author: Vitalii Tylyk
  # author: ["Me", "You"] # multiple authors
  images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: true
  hidemeta: false
  hideSummary: false
  showtoc: true
  tocopen: true

  assets:
    disableHLJS: true

  label:
    text: "Vitalii Tylyk"
    icon: /apple-touch-icon.png
    iconHeight: 35

  # profile-mode
  profileMode:
    enabled: true # needs to be explicitly set
    title: Vitalii Tylyk's blog
    subtitle: ".NET / Sitecore / Architecture / DevOps"
    imageUrl: "media/avatar.jpg"
    imageWidth: 160
    imageHeight: 160
    imageTitle: Vitalii
    buttons:
      - name: Posts
        url: posts
      - name: About me
        url: about-me

  socialIcons:
    - name: twitter
      url: "https://twitter.com/vitalii_tylyk"
    - name: linkedin
      url: "https://www.linkedin.com/in/vitalii-tylyk-ba1b6b63/"
    - name: github
      url: "https://github.com/vitaliitylyk"

  analytics:
    google:
      SiteVerificationTag: "7RIl7MHRVvum_KgTtZvnTWnCkB3_l7jcYFoDi8yrxIY"
    bing:
      SiteVerificationTag: "CE8C5B7610CFC9BB80E87615DF4366B5"
    yandex:
      SiteVerificationTag: "b64d46d08a0ae695"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  editPost:
    URL: "https://github.com/vitaliitylyk/blog.vitaliitylyk.com/content"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
menu:
  main:
    - name: Archive
      url: /archives/
      weight: 1
    - name: Search
      url: /search/
      weight: 5
    - name: Categories
      url: /categories/
      weight: 10
    - name: Tags
      url: /tags/
      weight: 20
    - name: About me
      url: /about-me/
      weight: 30
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: false
markup:
  highlight:
    noClasses: true
    # anchorLineNos: true
    codeFences: true
    guessSyntax: true
    # lineNos: true
    style: monokai
